### ISSUE TITLE
Deleting a yellow boost piece will give you a standard track piece

### ISSUE THREAD

**Issue by jaller94** [xem/js13k19#1]
1. Open level 3
2. Place down your yellow boost track pieces
3. Start the level (does not matter if you complete it or not)
4. Back in the editor, deleting placed down boost pieces (Press Del while focusing them) will give you standard tracks instead of boost pieces.

![tm](https://user-images.githubusercontent.com/10872136/64918085-a59cde00-d799-11e9-9f09-8e8c286f8a97.gif)

**Comment by xem** [comment]
Thanks a lot! it's fixed on http://xem.github.io/js13k19 and I submitted an updated build to the organizer of js13k :)

**Comment by xem** [comment]
Thanks a lot! it's fixed on http://xem.github.io/js13k19 and I submitted an updated build to the organizer of js13k :)

**Comment by jaller94** [comment]
Wow.. I didn't know updates/fixes are allowed.
I found a typo in my typing game after the deadline. 😒
